[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.5"

[prune]
  go-tests = true
  unused-packages = true
